# Generated by Django 6.0.3 on 2026-05-12 02:32

from django.db import migrations, models


def migrar_status_existente(apps, schema_editor):
    Inscricao = apps.get_model('inscricoes', 'Inscricao')

    Inscricao.objects.filter(ativa=True).update(status='aprovada')
    Inscricao.objects.filter(ativa=False).update(status='recusada')


def reverter_status_existente(apps, schema_editor):
    Inscricao = apps.get_model('inscricoes', 'Inscricao')

    Inscricao.objects.all().update(status='pendente')


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_inscricao_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20),
        ),
        migrations.RunPython(
            migrar_status_existente,
            reverter_status_existente
        ),
    ]
