# Generated by Django 6.0.3 on 2026-05-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_inscricao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
