# Generated by Codex on 2026-05-28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_aula_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='horario',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['-data', '-horario', '-data_criacao']},
        ),
    ]
