# Generated by Django 6.0.5 on 2026-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0006_aula_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='certificado_liberado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='certificado_liberado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
