# Generated by Django 6.0.5 on 2026-06-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0007_inscricao_certificado_liberado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='certificado_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
