# Generated by Django 6.0.5 on 2026-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0008_inscricao_certificado_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='certificado_arquivo',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='certificado_conteudo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='certificado_nome_arquivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='certificado_tipo_arquivo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
