# Generated by Django 6.0.5 on 2026-06-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0009_remove_inscricao_certificado_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='curso_concluido',
            field=models.BooleanField(default=False),
        ),
    ]
