# Generated by Django 6.0.3 on 2026-06-05 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0011_produto_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('conteudo', models.BinaryField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='inscricoes.produto')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('conteudo', models.BinaryField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='inscricoes.servico')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
