# Generated by Django 6.0.3 on 2026-06-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0013_alter_servico_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('doacao', 'Doacao'), ('parceria', 'Parceria')], max_length=20)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('nova', 'Nova'), ('em_analise', 'Em analise'), ('respondida', 'Respondida'), ('arquivada', 'Arquivada')], default='nova', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
