# Generated by Django 6.0.3 on 2026-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0014_solicitacaocontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='whatsapp_contato',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
