# Generated by Django 6.0.3 on 2026-06-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0016_alter_solicitacaocontato_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_chave_ong', models.TextField(blank=True, help_text='Aceita e-mail, CPF, telefone, chave aleatoria ou copia e cola.', verbose_name='Chave PIX da ONG')),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao do sistema',
                'verbose_name_plural': 'Configuracoes do sistema',
            },
        ),
    ]
