# Generated by Django 6.0.3 on 2026-06-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0017_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='whatsapp_contato',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
